### PR TITLE
Use serviceOptions option in azure.createBlobService

### PR DESCRIPTION
**Pull request by SomaticIT**
Allow to use serviceOptions option to set storage account connection strings or credentials.

You can find the documentation of the azure.createBlobService method at: http://dl.windowsazure.com/nodedocs/global.html#createBlobService

### CODE REVIEW

**Comment by paulomcnally** [comment]
ping @jstott

**Comment by SomaticIT** [comment]
Is this project dead ?

**Comment by paulomcnally** [comment]
@SomaticIT check this: https://github.com/nodenica/grunt-azure-blob

**Comment by SomaticIT** [comment]
I couldn't wait, I created a more complete grunt azure task : https://github.com/spatools/grunt-azure.
It was just to know.

Thanks.

**Pull request closed without merging**
